### ISSUE TITLE
Use `require_relative`

### ISSUE THREAD

**Issue by kohder** [Eppo-exp/ruby-sdk#7]
I just started our trial integration with Eppo but immediately hit a blocker:
`uninitialized constant EppoClient::Config (NameError)`

This is because my project has a `config.rb` file so the require statement in `eppo_client.rb` is not resolving to the one in Eppo's gem. This is normally not an issue in gems (or at least reduces chances of this happening) when they put the majority of their files in a subdirectory under `lib/`. In this case it would be `lib/eppo_client/`. The only rb file in `lib/` would be `eppo_client.rb` and it would require the other files with `require_relative`.
Could we get a fixed version of the gem?

Also, there is a line of Python in the Ruby docs: https://docs.geteppo.com/feature-flags/sdks/ruby/
See `from eppo_client.config import Config`

**Comment by leoromanovsky** [comment]
Thanks for creating this ticket! We are looking at the issues you've created asap to unblock you.
