### ISSUE TITLE
EppoClient#init can't find gemspec file

### ISSUE THREAD

**Issue by kohder** [Eppo-exp/ruby-sdk#8]
```
/<redacted>/vendor/bundle/ruby/3.2.0/gems/parse_gemspec-1.0.0/lib/parse_gemspec/specification.rb:8:in `load': file: eppo-server-sdk.gemspec (ParseGemspec::GemspecFileNotFoundError)
	from /<redacted>/vendor/bundle/ruby/3.2.0/gems/eppo-server-sdk-0.2.0/lib/eppo_client.rb:35:in `init'
	from /<redacted>/config/initializers/eppo.rb:4:in `<top (required)>'
	from /<redacted>/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.1/lib/active_support/dependencies.rb:326:in `load'
	from /<redacted>/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.1/lib/active_support/dependencies.rb:326:in `block in load'
	from /<redacted>/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.1/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /<redacted>/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.1/lib/active_support/dependencies.rb:326:in `load'
	from /<redacted>/vendor/bundle/ruby/3.2.0/gems/railties-6.1.7.1/lib/rails/engine.rb:681:in `block in load_config_initializer'
	from /<redacted>/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.1/lib/active_support/notifications.rb:205:in `instrument'
```

The `init` method in `eppo_client.rb` is trying to parse the gemspec file but that file is not being packaged up into the gem. Even if it were, the pathing isn't correct so it wouldn't find it the way it's written now. I see that it's doing this to get the version number. May I suggest a better pattern for this is to have a simple version.rb in `lib/eppo_client/` that is read by both the gemspec file and by this init method. You can see a great example in how this project is doing it: https://github.com/sidekiq/sidekiq

Can we please get a fixed gem cut?

**Comment by sameerank** [comment]
Hi @kohder, I just published a new gem version (v0.2.3) with the fixes you proposed.

Really appreciate the feedback! Please feel free to let us know if anything else comes up.
